function data = importfile_coord(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COORD6 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  COORD6 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Coord6 = importfile("G:\My Drive\Work\1-UCPSYCH\Teaching\Courses\PSYC 3045\Lab Demos\3-Coordination\CoordLab\Coord6.trc", [7, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Nov-2022 09:17:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [7, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "time", "X1", "Y1", "Z1", "X2", "Y2", "Z2", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14"];
opts.SelectedVariableNames = ["VarName1", "time", "X1", "Y1", "Z1", "X2", "Y2", "Z2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var9", "Var10", "Var11", "Var12", "Var13", "Var14"], "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end